# -*- coding: utf-8 -*-
"""marketing .b

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RAtrkz8chcsRR2jz2IavvEfgQJkcdDf7
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score, mean_absolute_error

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("mediamix_sales.csv")
df.head()

print(df.columns)
print(df.info())
print(df.describe())
print(df.isnull().sum())

"""CLEAN + SORT DATA"""

df["Time"] = pd.to_datetime(df["Time"])
df = df.sort_values("Time")

df = df.dropna()
df = df.drop_duplicates()

"""DEFINE TARGET + FEATURES"""

y = df["sales"]
X = df.drop(columns=["sales", "Time"])

"""Correlation heatmap"""

plt.figure(figsize=(12,6))
sns.heatmap(df.corr(), cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

"""Exploratory Data Analysis (EDA)

Sales trend
"""

plt.figure(figsize=(10,5))
plt.plot(df["sales"])
plt.title("Sales Over Time")
plt.show()

"""Feature Engineering (VERY IMPORTANT MMM STEP)

STEP 6: ADSTOCK TRANSFORMATION (CORE MMM CONCEPT)
"""

def adstock(series, decay=0.5):
    result = []
    carry = 0

    for x in series:
        carry = x + decay * carry
        result.append(carry)

    return np.array(result)

X_adstock = pd.DataFrame()

for col in X.columns:
    X_adstock[col] = adstock(X[col], decay=0.5)

"""SATURATION (Diminishing Returns)"""

X_sat = np.log1p(X_adstock)

"""STANDARDIZATION"""

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_sat)

"""MODEL 1: LINEAR REGRESSION (BASELINE)"""

lr = LinearRegression()
lr.fit(X_scaled, y)

pred_lr = lr.predict(X_scaled)

print("Linear R2:", r2_score(y, pred_lr))

"""MODEL 2: RIDGE REGRESSION (BEST MMM MODEL)"""

ridge = Ridge(alpha=1.0)
ridge.fit(X_scaled, y)

pred_ridge = ridge.predict(X_scaled)

print("Ridge R2:", r2_score(y, pred_ridge))

"""MODEL 3: LASSO REGRESSION"""

lasso = Lasso(alpha=0.5)
lasso.fit(X_scaled, y)

pred_lasso = lasso.predict(X_scaled)

print("Lasso R2:", r2_score(y, pred_lasso))

"""MODEL COMPARISON"""

results = pd.DataFrame({
    "Model": ["Linear", "Ridge", "Lasso"],
    "R2": [
        r2_score(y, pred_lr),
        r2_score(y, pred_ridge),
        r2_score(y, pred_lasso)
    ],
    "MAE": [
        mean_absolute_error(y, pred_lr),
        mean_absolute_error(y, pred_ridge),
        mean_absolute_error(y, pred_lasso)
    ]
})

results

"""BEST MODEL (RIDGE)"""

final_model = ridge
final_pred = pred_ridge

"""ACTUAL VS PREDICTED"""

plt.figure(figsize=(12,5))
plt.plot(y.values, label="Actual Sales")
plt.plot(final_pred, label="Predicted Sales")
plt.legend()
plt.title("MMM Model Fit (Ridge)")
plt.show()

"""CHANNEL CONTRIBUTION (IMPORTANT)"""

importance = pd.DataFrame({
    "Channel": X.columns,
    "Coefficient": ridge.coef_
})

importance["AbsImpact"] = importance["Coefficient"].abs()
importance["Contribution_%"] = (
    importance["AbsImpact"] / importance["AbsImpact"].sum()
) * 100

importance.sort_values("Contribution_%", ascending=False)

"""ROI CALCULATION"""

df["total_spend"] = X.sum(axis=1)

roi = df["sales"].sum() / df["total_spend"].sum()

print("Overall ROI:", roi)

"""BASELINE FUNCTION FOR OPTIMIZATION"""

def predict_sales(input_spend):
    input_df = pd.DataFrame([input_spend], columns=X.columns)

    adstocked = pd.DataFrame()

    for col in input_df.columns:
        adstocked[col] = np.log1p(adstock(input_df[col], decay=0.5))

    scaled = scaler.transform(adstocked)

    return ridge.predict(scaled)[0]

"""BASELINE SALES"""

current_spend = X.mean()
baseline_sales = predict_sales(current_spend)

print("Baseline Sales:", baseline_sales)

""" BUDGET OPTIMIZATION SIMULATION
Scenario 1: Shift budget TV → Digital
"""

scenario1 = current_spend.copy()

if "tv_sponsorships" in scenario1.index:
    scenario1["tv_sponsorships"] *= 0.8

if "Social" in scenario1.index:
    scenario1["Social"] *= 1.2

sales1 = predict_sales(scenario1)

print("Scenario 1 Sales:", sales1)

"""Scenario 2: Boost High-performing channels"""

scenario2 = current_spend.copy()

top_channels = importance.sort_values("Contribution_%", ascending=False)["Channel"].head(3)

for col in top_channels:
    scenario2[col] *= 1.2

sales2 = predict_sales(scenario2)

print("Scenario 2 Sales:", sales2)

"""SCENARIO COMPARISON"""

scenario2 = current_spend.copy()

top_channels = importance.sort_values("Contribution_%", ascending=False)["Channel"].head(3)

for col in top_channels:
    scenario2[col] *= 1.2

sales2 = predict_sales(scenario2)

print("Scenario 2 Sales:", sales2)

"""CHANNEL EFFICIENCY (LIFT ANALYSIS)"""

lift = {}

for col in X.columns:
    temp = current_spend.copy()
    temp[col] *= 1.2

    lift[col] = predict_sales(temp) - baseline_sales

lift_df = pd.DataFrame.from_dict(lift, orient="index", columns=["Sales_Lift"])
lift_df.sort_values("Sales_Lift", ascending=False)

df.to_csv("mmm_final_dataset.csv", index=False)

from google.colab import files
files.download("mmm_final_dataset.csv")

with pd.ExcelWriter("MMM_Output.xlsx") as writer:
    df.to_excel(writer, sheet_name="Raw_Data", index=False)
    importance.to_excel(writer, sheet_name="Channel_Impact", index=False)

"""Export multiple datasets (recommended for MMM project)
Example: model output table
"""

df["predicted_sales"] = final_pred
df.to_csv("mmm_with_predictions.csv", index=False)
files.download("mmm_with_predictions.csv")

importance.to_csv("channel_contribution.csv", index=False)
files.download("channel_contribution.csv")

importance_dict = importance.set_index("Channel")["Contribution_%"].to_dict()

for col in X.columns:
    df[col + "_contribution"] = importance_dict.get(col, 0)

df.to_csv("MMM_Final_Dashboard.csv", index=False)
files.download("MMM_Final_Dashboard.csv")

"""scenario results"""

df.to_excel("mmm_data.xlsx", index=False)

# ensure time format
df["Time"] = pd.to_datetime(df["Time"])

# predicted sales (from your model)
df["predicted_sales"] = final_pred

# total spend
spend_cols = [col for col in df.columns if col not in ["Time", "sales", "predicted_sales"]]
df["total_spend"] = df[spend_cols].sum(axis=1)

# ROI
df["roi"] = df["sales"] / df["total_spend"]

# clean column names (Power BI friendly)
df.columns = df.columns.str.replace(" ", "_")

